#!/usr/bin/env bash
#  Bash script that loops from 1 to 10 and
MESSAGE="Best School"
COUNTER=1

while [ $COUNTER -le 10 ]; do
	if [ $COUNTER == 4 ]; then
		echo "bad luck"
	elif [ $COUNTER == 8 ]; then
		echo "good luck"
	else
		echo "$MESSAGE"
	fi
	COUNTER=$((COUNTER + 1))
done
